### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by chipfrog** [EssKayz/CertificateManager#1]
Lähdekoodi ladattu 30.9.2019 klo 18.00 ja sovellusta testattu Herokussa ja paikallisesti.

**Yleistä:**

Lähdekoodi oli rakenteeltaan selkeää ja helposti ymmärrettävää ja kansiorakenne looginen.
Sovellus toimi testauksen aikana muutamaa virhetilannetta lukuun ottamatta oikein hyvin. Testasin sisäänkirjautumista, uuden valmistajan ja tuotemallin luomista, tuotteen lisäämistä käyttäjälle ja sen poistamista, sekä uuden käyttäjän rekisteröimistä. Edellä mainitut toiminnot sujuivat ilman ongelmia. Sovellus ei esimerkiksi antanut luoda toista käyttäjää samalla nimimerkillä , vaan antoi asianmukaisen virheilmoituksen. Sovellus varmisti myös, ettei käyttäjä lisää samalla sarjanumerolla varustettua tuotetta uudestaan. Myös _Top Manufacturers_ -lista päivittyi uusien tuotteiden lisäämisen myötä ja asettui oikeaan järjestykseen.

Oli ilo huomata, että sivun ulkoasuun on kiinnitetty huomiota. Esim. yläpalkin kuvakkeet ja rekisteröitymisikkunan _Terms and Conditions_ -hyväksymispainike olivat kiva lisä, kuten myös _New equipment_ -napista tapahtuva siirtymä. Käytettävyyden saralla salasanan oikeinkirjoituksen varmistaminen rekisteröidyttäessä oli myös hyvä huomio.

**Huomioita:**

* Sama valmistaja ja tuotemalli on mahdollista lisätä useita kertoja. Valmistajan/Tuotteen nimen uniikkius olisi hyvä validoida ja antaa jokin virheilmoitus, jos samanniminen valmistaja tai tuotemalli yritetään lisätä uudestaan.
* Jos uutta tuotemallia yrittää lisätä ennen kuin on lisännyt yhtään valmistajaa, aukeaa _jinja2.exceptions.TemplateNotFound_ -virhesivu.
* _Terms and Conditions_ -näkymä ei ollut responsiivinen. Se ei reagoinut ruksiin eikä skrollaamiseen. Näkymästä pääsi pois vain selaimen takaisin-painikkeella.
* Olisi kätevää jos uuden käyttäjän rekisteröimisen jälkeen sisäänkirjautuminen tapahtuisi automaattisesti.
* Kuvaus sovelluksen toiminnasta _Readme_:ssa voisi kenties olla hieman kattavampi. Sovelluksen idea aukesi minulle paremmin vasta, kun testasin Herokussa olevaa versiota, jossa oli jo valmiiksi dataa.
* _Terms and Conditions_:in hyväksyminen kaduttaa :)

Kaiken kaikkiaan hyvää työtä!

**Comment by EssKayz** [comment]
Myönnettäköön, että tuo terms and conditions näkymä on siis feature, koska siitä onkin tarkoitus päästä pois ainoastaan hyväksymällä ;) ... Pitäähän sitä lisätä pieniä easter eggyjä.

mutta joo, erittäin hyviä pointteja. tajusin tuota lukiessani että olin jossakin kohtaa miettinyt juuri tuota tuotteen lisäämistä ennen manufacturerin olemassa oloa, mutta sitten se vain jäin unholaan kun se toimi (koska data oli olemassa).

Täytyykin myös tuo sarjanumeroihin ja nimiin perustuva uniikkius saada noihin tuotenimiin ja valmistajiin, eipä käynyt mielessäkään tuokaan vaihtoehto :)

Kiitoksia hyvästä palautteesta! Alankin tästä noita asioita korjailemaan :)

**Comment by EssKayz** [comment]
Hmm, itse asiassa tuo toimiikin ilmeisesti eri tavalla kuin mitä silloin alussa testaillessani. Ei ihan NOIN aggressiivisesti kuuluisi jäädä ei-reaktiiviseksi, pitääkin korjata mikä lie sen on rikkonut.
